### ISSUE TITLE
How to enable Perspective API?

### ISSUE THREAD

**Issue by kzkszk** [conversationai/perspectiveapi#100]
I would like to enable Perspective API.

I followed this instruction.
https://support.perspectiveapi.com/s/docs-enable-the-api

First, I tried gcloud command.
```
gcloud services enable commentanalyzer.googleapis.com
```
Then, I got this error message.
```
(gcloud.services.enable) PERMISSION_DENIED: The caller does not have permission
```
When I enabled other services, 
```
gcloud services enable speech.googleapis.com
gcloud services enable cloudfunctions.googleapis.com
```
I didn't get an error message.
```
Operation "operations/acf.6a796efd-56dc-4f16-8fe9-cd858de467e6" finished successfully.
```

Next, I tried  Cloud Console.

> Navigate to the Perspective API overview page and click "Enable".

I clicked this link.
https://pantheon.corp.google.com/apis/api/commentanalyzer.googleapis.com/overview?debugUI=DEVELOPERS&project=wikidetox-viz&folder=&organizationId=

Then I moved to "moma inside google" page and I didn't know what to do.

Could you tell me how to enable Perspective API, please?

**Comment by ralmarzoog** [comment]
Hi,

Sorry you're having trouble enabling the API. Have you filled out the [registration form](https://docs.google.com/forms/d/e/1FAIpQLSdhBBnVVVbXSElby-jhNnEj-Zwpt5toQSCFsJerGfpXW66CuQ/viewform)? Within an hour of filling out the form, you should receive an email confirming that you can view and enable the API in Google Cloud.

**Comment by kzkszk** [comment]
Thank you very much for your comment. I filled out the form and I am waiting for an confirming email.

**Comment by kzkszk** [comment]
I can enable Perspective API. Thank you so much!
