### ISSUE TITLE
Support of Chinese Mandarin

### ISSUE THREAD

**Issue by giranntu** [conversationai/perspectiveapi#107]
Hi experts, 
would like to know if it is possible to develop the Chinese(ZH-TW) language support? 

It would be many of the use case in Taiwan and live streaming real time detection. please let me know if there is the plan of support Chinese language. 

Thanks

**Comment by oliviaredfield** [comment]
Hi there!
We're hoping to add Chinese in the future. If you're able to, we'd encourage you to submit data via our [data submission form ](https://docs.google.com/forms/d/e/1FAIpQLScAivfFHiwq08JfsHuIkTbdECLK0nSmyBi4JMvaqDrom2aVQw/viewform?c=0&w=1) to help us in the development process.
