### ISSUE TITLE
api down or removed?

### ISSUE THREAD

**Issue by DumbGameMaker** [conversationai/perspectiveapi#108]
I am using this api for a [discord bot](https://daleonai.com/build-your-own-ai-moderator-bot-for-discord-with-the-perspective-api) and when I go to the google cloud panel the api doesn't seem to exist.

**Comment by Isaacyipdeen** [comment]
same here. might have been removed.

**Comment by sorensenjs** [comment]
While PerspectiveAPI remains free to use, you must now request access
before it will be visible to your cloud project
https://github.com/conversationai/perspectiveapi/tree/master/1-get-started#request-access-to-the-api
