### ISSUE TITLE
German language support 

### ISSUE THREAD

**Issue by BilalReffas** [conversationai/perspectiveapi#11]
Is the german language supported?

**Comment by iislucas** [comment]
At the moment we only have datasets in English; so we don't have any German models. But if you know of any, do point them our way. I'd love to build models for more languages.

**Comment by BilalReffas** [comment]
Mhh okay 👌! How can I help you to push more languages? Translation?

**Comment by iislucas** [comment]
We're looking for people and organizations who have datasets in other languages, and we are exploring using same methodology we used for English on wikipedia (https://meta.wikimedia.org/wiki/Research:Detox) applied to other languages. We did some experiments with Translation, but toxic language tends not to be translated very well.

**Comment by BilalReffas** [comment]
Yes this way makes much more sense. Unfortunately I do not have datasets in german.:(

**Comment by dieviehper** [comment]
Hey iislucas,
in what format you need the german dataset? I'am the admin of a very big german forum and would love to give perspectiveapi a try.

**Comment by cjadams** [comment]
Thanks! You can submit datasets to[ this form](https://docs.google.com/forms/d/e/1FAIpQLScAivfFHiwq08JfsHuIkTbdECLK0nSmyBi4JMvaqDrom2aVQw/viewform?c=0&w=1) help Perspective expand into more languages.  There is info on the form about the ideal format.

**Comment by raqueljeni** [comment]
Sharing an update that German is now supported by Perspective API. You can find additional information about available languages here: https://github.com/conversationai/perspectiveapi/blob/master/2-api/models.md.
