### ISSUE TITLE
How should I pre-process texts with multiple single quotes?

### ISSUE THREAD

**Issue by aaronsarkissian** [conversationai/perspectiveapi#15]
This command returns this error:
```
curl -H "Content-Type: application/json" --data \
, >     '{comment: {text: "They're stupid, it's getting warmer, we should enjoy it while it lasts."},
v1>       languages: ["en"],
>       requestedAttributes: {TOXICITY:{}} }' \
>     https://commentanalyzer.googleapis.com/v1alpha1/comments:analyze?key=MY_KEY
curl: (6) Could not resolve host: stupid,
curl: (3) [globbing] unmatched close brace/bracket in column 56
{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Closing quote expected in string.\n\n^",
    "status": "INVALID_ARGUMENT"
  }
}
```
After removing the single quotes it works just fine. I also tried scape character didn't help.

**Comment by ojensen5115** [comment]
If you're pasting data into your shell you'll need to shell-escape it (right now, the apostrophe in `They're` is terminating the string that you begin with `'{comment`). Assuming you're using bash, try throwing a backslash (\) in front of them.

**Comment by aaronsarkissian** [comment]
@ojensen5115 I tried the backslash in shell, didn't help. There should be no (`'`) if you are using in terminal I think. But yeah I tried in NodeJs and it worked just fine.

**Comment by iislucas** [comment]
This problem here is actually just a bash-quoting thing; you can evaluate that string like this: 

```
curl -H "Content-Type: application/json" --data \
  "{ comment: { text: 'They\\'re stupid, it\\'s getting warmer, we should enjoy it while it lasts.' }, 
     languages: ['en'],
     requestedAttributes: {TOXICITY:{}} }" \
  https://commentanalyzer.googleapis.com/v1alpha1/comments:analyze?key=YOUR_KEY
```

Bash quoting is kind of tricky; see the [bash guide](https://www.gnu.org/software/bash/manual/html_node/Quoting.html) to learn more.

**Comment by aaronsarkissian** [comment]
@iislucas Thank you sir.
