### ISSUE TITLE
Investigage other score than harassement / toxicity

### ISSUE THREAD

**Issue by gagarine** [conversationai/perspectiveapi#17]
Harassment is one thing, but generally 80% of comments are simply stupid and reading them is a loss of time. Would be super cool if I can filter out all the stupid comment and keep only the bright one.
Right now it's more a sanitisation tool that really improving conversation.

Take your own example:
![screen shot 2017-07-14 at 06 16 30](https://user-images.githubusercontent.com/164074/28198139-0903b1bc-685c-11e7-9903-e894f9ec5216.png)

All the comments don't really bring something new or relevant on the subject of climate change.

**Comment by iislucas** [comment]
You might be interested in the unsubstantial classifier then: https://github.com/conversationai/perspectiveapi/blob/master/api_reference.md#models
As well as some of the other models.  Of course there are different levels of substantial too, but this is a step in the direction you are thinking.
