### ISSUE TITLE
What about collaborative filtering?

### ISSUE THREAD

**Issue by bhack** [conversationai/perspectiveapi#2]
We know that human attention and focus has a limit expecially in the computer mediated comunication overload. Not always upvoting (reddit, hackernews etc.) It is the best solution at scale.
It could be interesting especially in a discussion style  context.

**Comment by bhack** [comment]
@iislucas It is a really hard topic and I'm mainly interested in relation to [decentralized democracy applications](http://democracy.earth). Also in the context of the [DAO experiment](https://en.m.wikipedia.org/wiki/The_DAO_(organization) discussion scaling was really one of the main bottleneck for a productive discussion and deliberation. The user saliency bandwidth is limited and so how to let the discussion scale before voting? It is a cross topic between social science, group psicology, computer mediated communciation and machine learning.

**Comment by bhack** [comment]
Are you collaborating with [Sigdial](http://www.sigdial.org) on this subtopics?

**Comment by bhack** [comment]
[This year the conferenece](http://www.sigdial.org/workshops/conference18/) will be co-located also with Interspeech 2017.

**Comment by bhack** [comment]
See also https://cmc-corpora2017.eurac.edu

**Comment by iislucas** [comment]
Thanks! One things we have been wondering about is training LSTMs on the signals from collaborative filtering. I'll mark this as research to do.

**Comment by bhack** [comment]
https://research.googleblog.com/2017/05/coarse-discourse-dataset-for.html
