### ISSUE TITLE
Tone is not toxicity

### ISSUE THREAD

**Issue by rspeer** [conversationai/perspectiveapi#23]
The PerspectiveAPI model largely identifies comments with a negative tone. This is of course correlated with toxicity, but it is not the same thing. This was identified as a problem as early as the day of PerspectiveAPI's launch, by Caroline Sinders: https://medium.com/@carolinesinders/toxicity-and-tone-are-not-the-same-thing-analyzing-the-new-google-api-on-toxicity-perspectiveapi-14abe4e728b3

Is there a plan to distinguish tone and toxicity? Is the underlying model even sufficient to distinguish them?

**Comment by iislucas** [comment]
While I appreciate her expression of support working on this problem, it looks to me like the thesis in that post, namely that the toxicity data and model is actually identifying tone, is wrong. You can easily verify this yourself by testing examples on Watson's Tone Analyser here: https://www.ibm.com/watson/services/tone-analyzer/   

The 'Tone' scores generally don't correlate strongly with toxicity from our API. I haven't been able to find their Tone dataset (maybe its not public) so I don't know about the underlying training data. In particular, many threats are tone neutral but are clearly toxic. Similarly, curse words are often considered rude, and so according to the toxicity dataset (which is public and available on figshare: https://figshare.com/articles/Wikipedia_Talk_Labels_Toxicity/4563973), even positive expressions with curse words are often considered toxic, although not severely so (see the distinction between severe and mild toxicity in the dataset), even when they are positive in tone. 

When you look at the underlying nature of the data and questionnaire, it's actually quite easy to see why also. The questionnaire that we used to define toxicity is here: https://meta.wikimedia.org/wiki/Research:Detox 
It's not a sentiment/question about the emotional tone of the text. 

So, while there is certainly some correlation between sentiment, tone and toxicity; and you can certainly find some examples where scores are similar, there's also some big differences that you might not see if you only look at selected examples. I suggest instead, for example, scoring the Wikipedia dataset with tone models and looking at the results.
