### ISSUE TITLE
Incomplete Sentence in Documentation

### ISSUE THREAD

**Issue by pcjonathan** [conversationai/perspectiveapi#25]
FYI, In the [API reference](https://github.com/conversationai/perspectiveapi/blob/master/api_reference.md), the sentence "If you don't append an @VERSION_NUMBER to a model name" is incomplete. I assume it's meant to say that it'll use the latest version if one isn't specified?
Cheers

**Comment by iislucas** [comment]
Thanks, fixed! You guessed right :)
