### ISSUE TITLE
API limit questions

### ISSUE THREAD

**Issue by Foorack** [conversationai/perspectiveapi#30]
What is the API rate-limit? Does suggestCommentScore count towards it or does it have its own?
What is the maximum length of comment.text?

I couldn't find anything about this in the API reference. :slightly_smiling_face:

**Comment by KararTY** [comment]
Check #24.

> The API has a 10 qps limit

10 queries per second.

**Comment by iislucas** [comment]
Good question! I added a section to our docs: https://github.com/conversationai/perspectiveapi/commit/ef173d3989a4818d4a9abed516bba781e2470d06 

It looks like this: 

You can check your quota limits by going to [your google cloud project's Perspective API page](https://pantheon.corp.google.com/apis/api/commentanalyzer.googleapis.com/quotas), and check 
your projects quota usage at 
[the cloud console quota usage page](https://pantheon.corp.google.com/iam-admin/quotas).

**Comment by Foorack** [comment]
@iislucas Thank you very much for the information. However - just checking - was it intentional to link to Google's private corporate login? :slightly_smiling_face:
I am not a Google employee. Wouldn't it be better to instead link to the more public [Google Cloud Console API Quotas regarding PerspectiveAPI](https://console.cloud.google.com/apis/api/commentanalyzer.googleapis.com/quotas) page?

**Comment by iislucas** [comment]
oops, it was not! dangers of copy-pasting urls when systems munge your url... thanks, fixed!
