### ISSUE TITLE
Mathematical formulas give high toxicity

### ISSUE THREAD

**Issue by Foorack** [conversationai/perspectiveapi#31]
Examples: :slightly_smiling_face: 

`F = 3x^2` - 0.86421335
`f=4x+2` - 0.847609
`f=2x^2` - 0.86421335

Using the latest TOXICITY model.

**Comment by KararTY** [comment]
`Y = 3x^2` (0.5206719)
`y= 4x+2` (0.4463119)
`y=2x^2` (0.5206719)

It's because of the letter `F`. These results are still very high, but it's all about how you implement PerspectiveAPI into your project. And a project like this will bring all kinds of false positives.

**Comment by iislucas** [comment]
@KararTY is right about there being all sort of false-positives (and false-negatives); but reports like this are helpful, so thanks for sharing it @Foorack. 

A good way to explore the false-positives is to sort comments and look at the top (and bottom) of your set. For example, see this blog post: https://medium.com/the-false-positive/better-discussions-with-imperfect-models-91558235d442 

I suspect we'll need character levels models to make much progress on mathematical expressions; but we could at least start by increasing the number of data examples with mathematical formula. Perhaps by annotating talk pages of Wikipedia articles on mathematics.
