### ISSUE TITLE
Distinguishing threats and harmful comments

### ISSUE THREAD

**Issue by prattcmp** [conversationai/perspectiveapi#33]
All of the models I have used seem to have trouble distinguishing threats and harmful comments from vulgar language. They all seem to be heavily weighed against vulgar language instead of harmfulness.

Sometimes, simply using a curse word will have a higher `SEVERE_TOXICITY` score than a death threat. 

For example, saying "F*** you" returns a `SEVERE_TOXICITY` score of 0.89 and 
`ATTACK_ON_COMMENTER` score of `0.73`. Whereas, saying "I wanna shoot you" returns a `SEVERE_TOXICITY` score of `0.79` and `ATTACK_ON_COMMENTER` score of `0.83`.

Is there a particular model that is best at handling this kind of language? I would hope saying "I wanna kill/shoot you" would return an extremely high score (> 0.97) for both of these categories.

**Comment by iislucas** [comment]
We're actually working on this and hope to have a new model specially for threats, and a separate one for obscene language. I'll update this issue when it's released. I'll also be sending details to our announce list: https://groups.google.com/forum/#!forum/perspective-announce

**Comment by jetpack** [comment]
There is a new experimental `THREAT` model, released on 2018-08-31. Please try it out and let us know how it works!
