### ISSUE TITLE
Request for Perspective API

### ISSUE THREAD

**Issue by lijinfeng0713** [conversationai/perspectiveapi#35]
Hello,
 Recently I was engaged in research on text analysis and I have applied for your API for several days.  How long does the review take? I'm looking forward your reply
Thanks

**Comment by abeerunscore96** [comment]
It's been a week since I've applied too. Is there any way to get an update?

**Comment by mochat97** [comment]
Idk if this is still relevant but @lijinfeng0713 @abeerunscore96 I've ran into this issue before, but when I tried the API by [enabling it,](https://console.cloud.google.com/marketplace/details/google/commentanalyzer.googleapis.com?q=perspective%20comment%20analyzer%20api&id=d71706a6-4a64-4624-aacc-c21e7db691c3&project=covalence-a837b&authuser=1) it worked for me, and I also never received a confirmation email. This assumes that you both have Google Cloud Platform accounts already and and API key.

**Comment by iislucas** [comment]
We've now removed the requirement to be whitelisted to use the API, so you should be able to simply enable the API. But still keen to know how and what you use it for, so feel free to email or get in touch via github issues too :) 

(also, sorry for not seeing this earlier)

**Comment by abeerunscore96** [comment]
I've been whitelisted. I haven't started using the api yet. I'm glad to hear about whitelisting not being a requirement anymore though!
