### ISSUE TITLE
API Whitelist Access Issue

### ISSUE THREAD

**Issue by BluSpring** [conversationai/perspectiveapi#36]
![image](https://user-images.githubusercontent.com/20620191/43477250-4de4db90-952d-11e8-8f89-30d7e405c26f.png)
![image](https://user-images.githubusercontent.com/20620191/43477323-730c731a-952d-11e8-8871-c9b1b36c86ad.png)
I was already whitelisted for the API. How the heck do I not have access to it .-.

**Comment by iislucas** [comment]
Thanks for getting in touch, and oh dear. That is the correct, and normal, way you enable the API; so something has gone wrong... 

I'll have a look and see what's up... sometimes cloud ACLs propagate more slowly than I'd like, so it may be worth just trying again too, but I'll try and find out, and maybe change our whitelisting process to leave more time between enabling access and emailing, assuming that's the issue.

**Comment by BluSpring** [comment]
I forgot to mention
I got the email on July 3rd, and I haven't got access yet and it's August 1st here :/

**Comment by easowers** [comment]
Hi BluSpring! We noticed an error with the access granted that day, but it's been corrected. Can you try again and let us know if you have access now?  Thanks!

**Comment by BluSpring** [comment]
Hey, I just tried again, and I now have access! Thanks for all your help, guys!
