### ISSUE TITLE
Abusive words attached with special characters gives low toxicity

### ISSUE THREAD

**Issue by vikasr111** [conversationai/perspectiveapi#39]
I have observed that when we form any abusive keywords separated with two specific characters -  ampersand (&) and underscore( _ ) the toxicity of the phrase is surprisingly low. Ideally, this should not happen. For other similar characters, it shows correct toxicity values. Explained with examples:

**Normal word**
"You suck" - toxicity (0.95)

**Separated with & and _**
"You_suck" - toxicity (0.19)
"You&suck" - toxicity (0.21)

**Other similar characters**
"You-suck" - toxicity (0.91)
"You#suck" - toxicity (0.94)

I hope other people might have observed this problem. It's surprising why the toxicity is not proper only for these two characters. It defeats the whole purpose.

**Comment by vikasr111** [comment]
Thanks for clarifying, John.

It's still surprising how the toxicity score is proper for all the special characters except two - ampersand (&) and underscore( _ ).

**Comment by iislucas** [comment]
Thanks for the nudge, we've actually made some good progress experimenting with char-level CNNs, you can find the code here: https://github.com/conversationai/conversationai-models/tree/master/experiments/tf_trainer/tf_char_cnn 

Overall, we've been able to make much better char-based models; our only worry is that they are likely to miss more "polite" hate. We're doing some evaluation on that to decide how to release new char-based models. Do you have a application that is especially sensitive to people trying to game model results?

**Comment by iislucas** [comment]
Thanks for the details! Indeed, there are a lot of easy ways to game ML models scores when the models are based on parsing token; char models do a lot for that, but as a short hack before char models are released in the API, if you have an pressing problem, you could replace characters you see people often to game your abuse detection, e.g. replace  "&" and "_ " with " ", before sending to the API. I generally don't advise such hacks as its better to fix the underlying ML, but for special cases it's worth considering. I'll update this thread when we release our char models in the API, and that I think will help you get more stable scores.
