### ISSUE TITLE
Can't find site to enable API

### ISSUE THREAD

**Issue by rueetschit** [conversationai/perspectiveapi#40]
I'm having a bit trouble to get started using the Perspective API. I got the mail that my email adress got whitelisted yesterday but now, when I click the link in the quick start guide to the Perspective API's overview page to enable it for my app, it won't load at all. I can't even find it in the API library. Is there a new site for the API or another way to generate a key? Thanks!

**Comment by cjadams** [comment]
Hi there! Sorry you are having trouble.  First you need to create a new cloud project and then, once that is created you can visit the Perspective API overview page in Google Cloud console to enable and create an API key.  Full address for the overview page is: (https://console.developers.google.com/apis/api/commentanalyzer.googleapis.com/overview)

**Comment by rueetschit** [comment]
Hi! Thanks for your answer. Unfortunately, I still can't access the page, even after creating multiple new projects. Here's what I get:
<img width="1163" alt="bildschirmfoto 2018-10-26 um 10 19 54" src="https://user-images.githubusercontent.com/44478646/47554035-bbe34680-d908-11e8-8774-c9c0b91854cc.png">

Do you know if I need to do something else to get permission to the API?

**Comment by easowers** [comment]
There was an error with our latest access approvals. Can you try again now?

**Comment by rueetschit** [comment]
Perfect! Now it works. Thanks for the fast help, it is very appreciated.

**Comment by easowers** [comment]
kasavin, can you email conversationai-questions@google.com with the email address you applied with? Thanks!

If anyone else is seeing this, please email as well.

**Comment by CarefulKarma0** [comment]
Hi Im getting an error saying "There was an error while loading. Please try again." Is there any way to fix this?
