### ISSUE TITLE
API Key not valid

### ISSUE THREAD

**Issue by spokerman12** [conversationai/perspectiveapi#51]
I'm sorry, I'm sure this is a silly question, but I can't seem to run the quickstart guide example:

```
$ curl -H "Content-Type: application/json" --data \
    '{comment: {text: "what kind of idiot name is foo?"},
      languages: ["en"],
      requestedAttributes: {TOXICITY:{}} }' \
    https://commentanalyzer.googleapis.com/v1alpha1/comments:analyze?key=YOUR_KEY_HERE
```
I'm getting either:
```
"API key not valid. Please pass a valid API key.",
or
</code> was not found on this server.  <ins>That’s all we know.</ins>
```

I've got my JSON from the Google API services cloud:
```
{
  "type": "service_account",
  "project_id": "mineria-usb-2019",
  "private_key_id": "FOOBAR",
  "private_key": "-----BEGIN PRIVATE KEY-----\nSPAMSPAM=\n-----END PRIVATE KEY-----\n",
  "client_email": "daniel@mineria-usb-2019.iam.gserviceaccount.com",
  "client_id": "114660020295843746934",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/daniel%40mineria-usb-2019.iam.gserviceaccount.com"
}

```

So, should I pass the curl's argument as 

```
$ curl -H "Content-Type: application/json" --data \
    '{comment: {text: "what kind of idiot name is foo?"},
      languages: ["en"],
      requestedAttributes: {TOXICITY:{}} }' \
    https://commentanalyzer.googleapis.com/v1alpha1/comments:analyze?key=SPAMSPAM
```
Instead of SPAMSPAM should it include the newline characters? Or perhaps even the '='? Or including the quotation marks and the -----BEGIN PRIVATE KEY and so on? I've tried several combinations and still no luck.

Thank you for your time.

**Comment by iislucas** [comment]
Hi, I think you've created a service account key instead of an API key in the Google Cloud Console. 

To create an API key, click on "Create Credentials" and then make sure to select "API Key", and I could recommend also restricting it to the "Perspective API".

**Comment by spokerman12** [comment]
Yep. It was as you suggested, iislucas. The "API Key" option is not visible in all screens, one head first to the Credentials menu, and then select "Create Credentials." Thank you.
