### ISSUE TITLE
`doNotStore` is named negatively instead of positively

### ISSUE THREAD

**Issue by iandunn** [conversationai/perspectiveapi#58]
### Problem

I think it's a best practice to name things with positive phrasing, rather than negative, because turning the setting _on_ means that you _don't_ get the thing described by the setting, which is the opposite of what you'd naturally expect, and makes you jump through a mental hoop to sort out what will happen, rather than the two just being aligned.

> Use positive and active wording for checkbox labels, so that it’s clear what will happen if the user turns on the checkbox. Avoid negations such as “Don’t send me more email,” which would mean that the user would have to check the box in order for something not to ([source](https://uxplanet.org/checkbox-and-toggle-in-forms-f0de6086ac41))

The documentation recognizes this and has to add extra explanations in order to clarify itself:

> Defaults to false (request data may be stored). 

When I'm exposing this setting to my users, I have to flip everything in the UI so that it's stated in the positive for them, to avoid confusion. That means that I have to add extra code to reverse things before I sent it to the API. That's not a huge amount of work, but it is an extra hassle that shouldn't be necessary.

### Proposed Solution

The setting should be named `store` instead, and be `true` by default.

For backwards-compatibility, a new `store` option could be added, and `doNotStore` could wrap that behind the scenes.

**Comment by sorensenjs** [comment]
I don't disagree, but this is probably infeasible without a major revision. Will keep this in mind for future versions.
