### ISSUE TITLE
Documentation related to need for pre-processing of comment (text).

### ISSUE THREAD

**Issue by jdd-software** [conversationai/perspectiveapi#7]
Do we need to pre-process comment?, remove @username, remove html formatting, remove intentional repetitions, non sentence chars ecc. Specification related to how the text should be pre-processed (if needed) seems missing

**Comment by iislucas** [comment]
Thanks, I'll update the docs. Comments are assumed to be utf8 raw text of the comment/text to be checked. Emoji and other non-ascii characters can be included. Raw HTML will probably result in lower performance.

**Comment by iislucas** [comment]
Updated the docs: 
https://github.com/conversationai/perspectiveapi/commit/d941486dd50fdb1eb35110217ef0787e9ca54639
