### ISSUE TITLE
Comment character limit

### ISSUE THREAD

**Issue by ghost** [conversationai/perspectiveapi#70]
The API documentation mentions a character limit of 3000 _bytes_  for analyzing comments, however [this comment](https://github.com/conversationai/perspectiveapi/issues/30#issuecomment-373233480) suggests that the character limit is 3000 _characters_ (using Unicode it could mean up to 12000 bytes).

Is the actual limit in bytes or characters? If it is in bytes, would you consider raising the limit to characters? I have an application that analyzes comments from a chat-based system, that allows up to 2000 unicode characters per comment. Having to go around the limitation of 3000 bytes per comment would be very unfortunate, as I'd have to split comments across multiple requests to fully cover the comment.

And as the API does not allow batch requests, this does mean that other comments get queued up and may be stalled on high activity.

**Comment by sorensenjs** [comment]
HI - sorry for the slow response, we've been discussing this however and it's a bit complicated. The 3000 character limit applied to an earlier model, and limits actually vary from model to model. At present we do have a 20K bytes limit for anything sent through our API, and this will return an error message if exceeded. Our popular TOXICITY model does truncate the input at approximately 1500 _tokens_, but there's no easy way for a client to see the tokenization results so what that translates to in terms characters is a little difficult to say. We will try to document this better in future models and will update our documentation to make this unclear situation more discoverable.

If you are asking with respect to a particular model attribute, or with respect to a particular input, I might be able to give more details.

**Comment by CharlotteDunois** [comment]
Would it be possible to raise the token limit for the toxicity model? As an alternative it would probably useful to return the amount of consumed bytes as part of the response, if not fully consumed.
