### ISSUE TITLE
Investigate "Stupid" scores

### ISSUE THREAD

**Issue by iislucas** [conversationai/perspectiveapi#9]
Thanks to @jdd-software for reporting it: 

"Currently comments with >0.5 Threshold are outputted with text PERSPECTIVE if they do not contain the word stupid (we had to many false positive on "Sorry I was stupid" ecc.)"

TODO: investigate base distribution for the word "stupid" and see if we can collect a dataset to stop the false-positives for things like "Sorry I was stupid".

**Comment by jdd-software** [comment]
We can help by providing feedback (0 or 1) with communityId:"StackOverflow" on live comments, however since we are "only" a Community team we do not have access directly to SE database as NickLarsen.

**Comment by iislucas** [comment]
Thanks for all the feedback!
We've just released TOXICITY@5 and also SEVERE_TOXICITY@1, these behave a good deal better on examples like this (although of course still a more work to do!). Would love to know if they work any better for you?
