### ISSUE TITLE
Openly available data

### ISSUE THREAD

**Issue by lucacampanella** [conversationai/perspectiveapi#90]
Hi guys, amazing work. You often cite the fact that data is publicly available, but I couldn't find it anywhere. Is there a place when I can download the training data (or part of it)?
Thanks a lot!
Luca

**Comment by sorensenjs** [comment]
Perspective is trained on a mixture of data sources, some that are not available publicly. Please see
https://www.kaggle.com/c/jigsaw-unintended-bias-in-toxicity-classification/data
for a 2M comment dataset that is available under CC_0 terms.
