### ISSUE TITLE
Contradictions in documentation about supported languages

### ISSUE THREAD

**Issue by anseal** [conversationai/perspectiveapi#96]
https://github.com/conversationai/perspectiveapi/blob/master/2-api/methods.md

says
> Currently, all production attributes only support **English, Spanish, and French**

https://github.com/conversationai/perspectiveapi/blob/master/2-api/models.md

says
>
```
Attribute name  Type      Description   Language
TOXICITY        prod      ...           en, fr, es, de, it, pt
```
issue https://github.com/conversationai/perspectiveapi/issues/11 is still open and there is a comment
> At the moment we **only have datasets in English**; so we don't have any German models

https://support.perspectiveapi.com/s/article/perspective-faqs
says
> Is the API available in my language?
Right now, Perspective API is only available for scoring **English-language** comments. Check out [Languages served by Perspective API](https://support.perspectiveapi.com/s/article/languages?ui-self-service-components-controller.ArticleTopicList.getTopics=1&r=98&ui-communities-components-aura-components-forceCommunity-seoAssistant.SeoAssistant.getSeoData=1&ui-self-service-components-controller.SimilarArticleItem.logArticleAccepted=1&other.X7S_ArticleRating.loadArticleRating=1&ui-knowledge-components-aura-actions.KnowledgeArticleVersionCreateDraftFromOnlineAction.createDraftFromOnlineArticle=1&ui-comm-runtime-components-aura-components-siteforce-qb.Quarterback.validateRoute=1&ui-force-components-controllers-recordGlobalValueProvider.RecordGvp.getRecord=1&ui-self-service-components-controller.ArticleView.getArticleHeaderDetail=1&ui-comm-runtime-components-aura-components-siteforce-recordservicecomponent.RecordServiceComponent.getArticleUrlNameAndVersionId=1
) for information about other languages.

When I follow the [link](https://support.perspectiveapi.com/s/article/languages?ui-self-service-components-controller.ArticleTopicList.getTopics=1&r=98&ui-communities-components-aura-components-forceCommunity-seoAssistant.SeoAssistant.getSeoData=1&ui-self-service-components-controller.SimilarArticleItem.logArticleAccepted=1&other.X7S_ArticleRating.loadArticleRating=1&ui-knowledge-components-aura-actions.KnowledgeArticleVersionCreateDraftFromOnlineAction.createDraftFromOnlineArticle=1&ui-comm-runtime-components-aura-components-siteforce-qb.Quarterback.validateRoute=1&ui-force-components-controllers-recordGlobalValueProvider.RecordGvp.getRecord=1&ui-self-service-components-controller.ArticleView.getArticleHeaderDetail=1&ui-comm-runtime-components-aura-components-siteforce-recordservicecomponent.RecordServiceComponent.getArticleUrlNameAndVersionId=1
) there's said
> Currently, Perspective API has production TOXICITY and SEVERE_TOXICITY models in the following languages:
> - English (en)
> - Spanish (es)
> - French (fr)
> - German (de)
> - Portuguese (pt)
> - Italian (it)

What is the current situation with languages support for TOXICITY?

**Comment by raqueljeni** [comment]
Thank you for flagging this! TOXICITY is currently supported in English (en), Spanish (es), French (fr), German (de), Portuguese (pt), and Italian (it). We will work to remove the contradictions you identified.
